Update main.yaml

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -23,10 +23,12 @@ jobs:
         with:
           python-version: '3.11'
 
-      - name: Install dependencies
+      - name: Check for requirements.txt
         run: |
-          python -m pip install --upgrade pip
-          pip install -r requirements.txt
+          if [ ! -f requirements.txt ]; then
+          echo "❌ requirements.txt not found!"
+          exit 1
+          fi
 
   run-tests:
     needs: install-dependencies
